### ISSUE TITLE
[APM-CI][Opbeans] Use correct environment variables for RUM agent config

### ISSUE THREAD

**Issue by jahtalab** [elastic/opbeans-node#38]
The environment variables used [here](https://github.com/elastic/opbeans-node/blob/master/server.js#L45) to generate RUM agent config are not the ones documented in the README.
The variables should be: 

- `ELASTIC_APM_JS_BASE_SERVER_URL` - Elastic APM Server URL for the
  client app (default: `http://localhost:3000`)
- `ELASTIC_APM_JS_BASE_SERVICE_NAME` - Elastic APM App Name for the
  client app (defaults to `name` from [opbeans-frontend package.json
  file](https://github.com/elastic/opbeans-frontend/blob/master/package.json)
- `ELASTIC_APM_JS_BASE_SERVICE_VERSION` - Elastic APM App Name for the
  client app (defaults to `version` from [opbeans-frontend package.json
  file](https://github.com/elastic/opbeans-frontend/blob/master/package.json)

cc @watson @Qard

**Comment by watson** [comment]
Good call 👍 

Would you mind making a PR?

**Comment by Qard** [comment]
So the correct format is _with_ the `BASE` part in there? All the services in apm-integration-testing currently expect the opposite.

**Comment by alvarolobato** [comment]
@kuisathaverat can you help with this when you work on the compose refactoring?

**Comment by gingerwizard** [comment]
Seems the README.md isn't actually consistent with the code here

**Comment by kuisathaverat** [comment]
it was resolved on https://github.com/elastic/opbeans-node/pull/60
