### ISSUE TITLE
Seed RUM agent with Distributed Tracing config options

### ISSUE THREAD

**Issue by watson** [elastic/opbeans-node#49]

**Comment by Qard** [comment]
I don't think this is currently possible, as opbeans-frontend is statically rendered and provides no way to pass the appropriate settings in. There's currently a hack with rum-config.js to set serviceName, serviceVersion and serverUrl, but those are the only settings hard-coded into the opbeans-frontend code. Also, there's the problem of that coming from a request to rum-config.js, not the page itself, therefore even if we _could_ provide other properties that way, it would point to the wrong transaction. 🤔

**Comment by watson** [comment]
You can see how opbeans-ruby project have done it here: https://github.com/elastic/opbeans-ruby/commit/72676346748083292998b7b29bd2230cf246fc9b
